clip:
  model_name: "ViT-B-16-plus-240"
  pretrained: "laion400m_e31"
  class_name: 'dots'
  num_prompts: 6
  temp: 0.07

superpixel:
  numSegments: 100
  sigma: 3

gnn:
  gnn_type: 'GAT'
  level: 'graph'
  heads : 1

