clip:
  model_name: "ViT-B-16-plus-240"
  pretrained: "laion400m_e31"
  class_name: 'green dots'
  num_prompts: 0
  temp: 0.07

superpixel:
  numSegments: 100
  sigma: 3.


loss:
  tau: 0.07
  num_negs: 64

st:
  mode: 'none'
  beta: 1.0

pad:
  pad_green: False

gnn:
  net_type: 'gnn'
  gnn_type: 'GAT'
  level: 'graph'
  heads: 1

prompt:
  linear_probe: False
  share_prompt: True



