clip:
  model_name: "ViT-B-16-plus-240"
  pretrained: "laion400m_e31"
  class_name: 'dots'
  num_prompts: 4
  temp: 0.07

superpixel:
  numSegments: 75
  sigma: 3

gnn:
  net_type: 'gnn'
  gnn_type: 'GCN'
  level: 'graph'
  heads : 1

prompt:
  linear_probe: False
  share_prompt: True

