clip:
  model_name: "ViT-B-16-plus-240"
  pretrained: "laion400m_e31"
  class_name: 'green dots'
  num_prompts: 0
  temp: 0.07

loss:
  tau: 0.07
  num_negs: 512

mask:
  ratio: 0.53
  num_seeds: 10 #during inference

norm:
  norm_layer: 'adain'


