clip:
  model_name: "ViT-B-16-plus-240"
  pretrained: "laion400m_e31"
  class_name: 'black dots'
  num_prompts: 0
  temp: 0.07

superpixel:
  numSegments: 200
  sigma: 3

loss:
  use_margin: True

pad:
  pad_green: True

gnn:
  net_type: 'gnn'
  gnn_type: 'GAT'
  level: 'graph'
  heads : 1

prompt:
  linear_probe: False
  share_prompt: True

